Repository GERGUSCANO/PROYECTO-INTEGRADOR, pull requests merged in 2022-10, with the labels that each got.

#6 agregar registro de formulario ieee 830
  product backlog.xlsx
  prototipos html/Ingreso.jpg
  prototipos html/recuperacion.jpg
  prototipos html/registro.jpg
  registro-formato-ieee-830-ArSalud.docx
Labels: documentation

#23 Documentacion
  Integrantes.md
  MVCAr-Salud.drawio.pdf
  README.md
  UMLAR-Salud.pdf
Labels: documentation, base de datos, Backend

#28 Backend
  basedatos.sql
  diagrama.png
Labels: Backend
